// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxwauckpccujkwfagogf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94d2F1Y2twY2N1amt3ZmFnb2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjI2NDgsImV4cCI6MjA2ODMzODY0OH0.lmKlbq0mu51-NtuWPEE3zCCPB93_FmCiKqaD_E8oI8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});